### ISSUE TITLE
EV and DV: Discussion

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#11]
Per @LarryFrank - Issue opened to discuss inclusion of EV
#9 

- EV included (explicitly)?
- EV as required?
- EV as optional?

**Comment by LarryFrank** [comment]
My opinion is “optional” – EV is not required for all certificates but if the implementation meets the EV requirements, then EV would be asserted – otherwise one of the other policies.

Larry

**Comment by konklone** [comment]
If we can avoid supporting EV, I think that would be positive for this root. The first principles of Extended Validation are already met by virtue of the fact that `.gov` and `.mil` addresses require extended validation in order to be registered in the first place.

The risk of someone fraudulently registering a `.gov` domain isn't part of our threat model (that's part of `.gov`'s). In the case of a DNS attack where someone resolves a fake `.gov` address to the target, they would be extremely unlikely to be able to produce an EV certificate. In the case of an attack where they intercept the connection to a valid `.gov` domain, the "real certificate" that an agency obtained would not be visible to the user.

I'm [fond of using this image](https://www.youtube.com/watch?v=X5H8JRULDOo) to describe the primary issue with relying on EV certificates as a defense layer:

<img width="713" alt="screen shot 2016-11-03 at 2 31 55 pm" src="https://cloud.githubusercontent.com/assets/4592/19979905/756baa0e-a1d2-11e6-8eb6-fcd03aaadf9f.png">

Since EV certificates are absent during an attack, their remaining benefit is of branding -- when a user shows up to the website in a non-attack scenario, they can see the name of the organization. And I don't think we need to prioritize branding very much, especially since `.gov` and `.mil` already have very powerful branding in the form of their TLD.

It's definitely my experience that some agency IT shops prefer Extended Validation certificates, but I think this is an opportunity for us to demonstrate some leadership to the federal community, as well as save a lot of time and cost by avoiding committing to doing the EV validation process.

**Comment by twbaldridge** [comment]
I recommend that EV is available, as an option. 

There are a number of USG sites that have invested in commercial EV certificates because they perceive it is important. If this capability is not offered in this USG capability it is a motivation for some Federal Departments and Agencies to continue acquiring commercial EV certificates. 

There may not be much real difference in Federal processes for USG issued certificates under EV or DV requirements. Typically, existing approval processes for FISMA, ATO, etc., are likely sufficient, or with minor enhancement, to meet the EV validation process requirements. 

All the same the public perception may see DV as less security.  It will never be easier than now to address this perception issue by including EV as an option. I realize that I am advocating a marginal additional investment based on an improved public perception and not an actual increase in general security. 

I will point out if a practice or policy to enforce EV were in place then there is actual value. This could be users who refuse to enter a site that doesn't present the "green" address bar. Or a technical enforcement on USG managed endpoints that look for the specific certificate OIDs.

**Comment by konklone** [comment]
> There may not be much real difference in Federal processes for USG issued certificates under EV or DV requirements. Typically, existing approval processes for FISMA, ATO, etc., are likely sufficient, or with minor enhancement, to meet the EV validation process requirements.

This would be an interesting to seek CABF input on (since they author the [EV guidelines](https://cabforum.org/extended-validation-2/) too). If the existing process of _getting_ a `.gov` domain is enough to suffice for EV, then it would be minimal work for an issuing federal CA. But I suspect the CA will have to do their own validation, and not rely on the dotgov.gov registry's existing processes. In addition, not every `.gov` hostname has an associated ATO, and if it meant reviewing accompanying documentation that could be a substantial barrier to automation.

> There are a number of USG sites that have invested in commercial EV certificates because they perceive it is important. If this capability is not offered in this USG capability it is a motivation for some Federal Departments and Agencies to continue acquiring commercial EV certificates.

You're right, it could be a motivation for them to acquire commercial certificates. So I am partly proposing that we motivate reduced reliance on EV certificates by not supporting it for a CA that federal IT departments will be _strongly_ incentivized to use. I think if you had "desire for EV" (whose benefits are only perception) compete with "desire for a federally issued certificate" (whose benefits can include actual security), that the desire for a federally issued certificate will win.

> I will point out if a practice or policy to enforce EV were in place then there is actual value. This could be users who refuse to enter a site that doesn't present the "green" address bar.

So far, there's no evidence users like that exist, in research or in anecdotal experience. I think any effective enforcement would have to come from the browser. Right now, the only EV-specific technical policies I'm aware of in browser-land are that SCTs are required in Chrome.

> Or a technical enforcement on USG managed endpoints that look for the specific certificate OIDs.

This is true, but you would get identical security value by having USG managed endpoints look for certificates that chain up to these roots.

**Comment by pzb** [comment]
@konklone the EV process is not about domain ownership, it is about verification of the certificate requester ("Applicant" or "Subscriber").  So the process of getting a .gov is not sufficient.  However it would probably be possible to create a single workflow that enables getting EV certs at the same time as registering a .gov domain name.

Based on my experience starting a CA, I would suggest at least documenting a valid process for getting an EV cert and having such audited.  This will allow making the decision in the future of whether you want to offer these certs or not.  If you don't have any audited process, you are going to be locked into the "No EV" decision for the long term.

**Comment by konklone** [comment]
Yeah, as much as I (obviously) don't think much of EV, I think the inability to easily change this decision later is a compelling point in favor of requesting that user agents enable EV treatment for this root, and to let the decision to actually issue them or not be dependent on the issuing CA. 

I don't love that it will require having an audited/documented process at the get go, and so if we go that way, perhaps we can coordinate with the `.gov` and `.mil` registrars to establish streamlined processes. 

It's definitely going to be time and money, though, and I find it hard to justify spending that time and money on what is currently effectively a placebo.

**Comment by weirdscience** [comment]
User perspective is EV or the green bar with the companies name is meant to be more trusted right? That seems like the intent of browsers. If USG does not support EV, it may give user impression that USG sites are less trustworthy if the majority of commercial sites are using them. Depends on how browsers determine to support EV in the future.

**Comment by konklone** [comment]
> If USG does not support EV, it may give user impression that USG sites are less trustworthy if the majority of commercial sites are using them.

I don't believe the majority of commercial sites use them. Some prominent examples of sites which do not: [Amazon.com](https://www.amazon.com) (the biggest online store in the world), [Google](https://www.google.com), and [Facebook](https://facebook.com).

In addition, the USG has `.gov` and `.mil` to communicate trust, and IMO those are the brands worth building.

**Comment by TLSrUS** [comment]
I agree that most sites don't seem to use EV, except for banks, investment houses, and other financial firms (and GitHub...).  Most users don't know what the green EV bar means.  I agree with pzb that it would be useful to include at least documenting a valid process for getting an EV cert, rather than leaving it out entirely, but make it optional.

**Comment by lachellel** [comment]
- Issue still open. 
- Outreach to agencies to determine need and policies

@twbaldridge

**Comment by konklone** [comment]
I'd like to pass on authoring and sending this communication. It's an issue I have strong opinions about, and I'd prefer to be able to express those as appropriate rather than focus on moderating the issue.

**Comment by LarryFrank** [comment]
First - I am not an EV fan and see little or no utility in the additional work to get one.  But I see little utility in all the extra work to get issued PIV over "medium-hardware" (as DoD defines it) either...
Second - as noted above, it is about perception not fact.  Commercial PKIs have sold the perception that EV is more trustworthy than DV but I don't see it as being that much of a difference in fact.  Mostly been bought by the financial services community.
Third, maybe it is me, but the utility seems to vary by browser.  IE makes a clear distinction - not able to tell the difference on Chrome (maybe a user setting?)
The real discussion should be actual cost and actual benefit (not potential relying party perception).  What is the cost of including it and what is the benefit.  Is someone NOT going to trust WWW.ARMY.MIL or MAX.GOV because the bar didn't turn green (assuming it does that on your browser with EV)?  Are there actual examples where someone refused to accept a web site that didn't have EV?  Since 99% of DoD systems today have DoD PKI - the people complaining are talking about "public trust" of the Root not lack of EV.  
What is the cost of the additional "auditing" and "procedure development" needed?  If there are no issuing CAs with the EV OID, then the need for EV specific auditing is only of the Root - that seems pretty straight forward as it doesn't actually issue any end user certs.  If some CA decides it needs to do EV, then the entity which stands it up needs to bear the cost of the extra effort at that level.

**Comment by LarryFrank** [comment]
> I'd like to pass on authoring and sending this communication. It's an issue I have strong opinions about, and I'd prefer to be able to express those as appropriate rather than focus on moderating the issue.

If DoD wants, I can draft the request - but need someone in CIO council circles to send.

**Comment by PaulSD** [comment]
Since max.gov was explicitly mentioned ...

We actually do use an EV cert for max.gov, login.max.gov, and piv.max.gov - simply because security is particularly important for those domains, so we wanted to go all out for them.  However, we don't use an EV cert for any of our other domains, and nearly all of our commonly used applications live on other domains.  This has been the case for many years now, yet I have never heard any reports of anyone noticing the difference, even though all of our users bounce directly between EV and non-EV MAX domains every time they log in to a MAX app.  In fact, while I consider myself to be a relatively security-conscious individual, I don't think I would have noticed the difference myself if I hadn't been the one who configured it.

So, just my $.02 - As currently implemented, and as currently perceived (or not) by users, EV certs provide no real value, and MAX would not have a problem with the US PKI deciding to not support EV.
