### ISSUE TITLE
Mozilla's proposed self-assessment of BR compatibility

### ISSUE THREAD

**Issue by konklone** [uspki/policies#119]
Just want to note this draft proposal by Mozilla to have applicant CAs provide their own self-assessment of BR compatibility in order to speed up the inclusion process:

https://wiki.mozilla.org/CA:BRs-Self-Assessment

**Comment by lachellel** [comment]
This is for us to review and update the CP and CPSs at least annually (and increment the version to show the updates, even if no changes were done). 

`CAs with included root certificates that have the websites trust bit set must do an annual self-assessment of their compliance with the BRs using the above template, and must update their CP and CPS documents at least once every year. You should indicate that this has happened by incrementing the version number and adding a dated changelog entry, even if no other changes are made to the CP and CPS documents.`

Do we want to specify this in Section 1.5 explicitly?  so that noone forgets?  :+1: 

- https://github.com/uspki/policies/blob/master/certificate-policy.md#15-policy-administration

**Comment by lachellel** [comment]
@weirdscience @techliaison @LarryFrank

Would this make sense to just add it to Section 1.5?  Using slightly updated terms.

**Comment by weirdscience** [comment]
1.5 or in section 8 (maybe 8.7)

"An annual self-assessment shall be conducted by any CA operating against this CP and accompanying CPS to show compliance with the latest version of the CAB Forum Baseline Requirements. The CA shall indicate the self-assessment annually by incrementing the version number and adding a dated changelog entry to the change record."

**Comment by techliaison** [comment]
We may actually want to split it
The annual CP review & update is an action of the PA in maintaining the CP and belongs in 1.5/1.5.1
Whereas the annual update of each CA’s CPS is the responsibility of each CA – both the Root and any issuing CAs – with a review/approval of the PA for the update.  We may want to leverage the issuing CA’s mandated quarterly self-audits as Ken mentions for the CPS requirement.

**Comment by LarryFrank** [comment]
The "self assessment" is a policy/practice statement analysis - not an "audit" - so it should all be in Section 1.5 (my opinion) and nothing in Section 8.  PMA does a policy review and then directs CAs to update and submit their CPS for approval based on the policy update.  In neither case is this an "audit."

**Comment by lachellel** [comment]
which is best for the policy updates?

**Comment by LarryFrank** [comment]
> which is best for the policy updates?

Section 9.12 "AMENDMENTS" seems the right place to put the requirement for an annual review and update of the CP and that any CP update should be followed by a review of the various CPSs under the CP to assess for impact.
