### ISSUE TITLE
5.2 Procedural Controls 

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#121]
- 5.2.1 Trusted roles
- 5.2.2 Number of Individuals Required per Task
- 5.2.3 Identification and authentication for each role
- 5.2.4 Roles requiring separation of duties

Which government requirements do we want to specify?
Take from Common CP as baseline iteration? Are there any issues with using Common CP first?

**Comment by jaspenc** [comment]
I recommend starting with the Common CP.  The designations of the trusted roles and the two person control requirements are based on 'industry best practices.'  After all, these folks have the keys to the kingdom, and since they already exist for the most part in the existing infrastructure, it's not like we are reinventing anything here.

**Comment by lachellel** [comment]
#136
