### ISSUE TITLE
Name Redaction: Discussion

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#13]
**Name Redaction**

- Scope: Name Redaction for publishing to CT Logs
- Allowing for name redaction is _not_ expected to be included

Please add references to open discussions, browser policies, and technical constraints here.

**Comment by lachellel** [comment]
Linking to #37

**Comment by lachellel** [comment]
What are the RFCs and current policies on redaction? Can we list those here, in prep for the CT Policy days and overall discussions for USG?

**Comment by konklone** [comment]
IETF-side:

* [RFC 6962](https://tools.ietf.org/html/rfc6962) - Original CT RFC, no mention of redaction.
* [RFC 6962-big draft 18](https://tools.ietf.org/html/draft-ietf-trans-rfc6962-bis-18) - Earlier draft of RFC 6962 sequel, last one to [include redaction](https://tools.ietf.org/html/draft-ietf-trans-rfc6962-bis-18#section-4.2).
* [RFC 6962-bis draft 24](https://tools.ietf.org/html/draft-ietf-trans-rfc6962-bis-24) - Latest draft of RFC 6962 sequel, no mention of redaction.
* [Draft stand-alone redaction spec](https://tools.ietf.org/html/draft-strad-trans-redaction-01), there to capture the work so far, but no clear path to adoption yet in any CT relying party.
* [Consensus call in IETF WG to drop redaction from main spec](https://www.ietf.org/mail-archive/web/trans/current/threads.html#02376) (I also participated a bit.)

Chrome-side:

* March 2016: [Chrome CT policy list discussion](https://groups.google.com/a/chromium.org/d/topic/ct-policy/vsTzv8oNcws/discussion) about whether Chrome should support name redaction (as specced out at the time in a draft of 6962-bis) in time for their enforcement action on Symantec in summer 2016. (I participated substantially.)
* [Chrome CT policy list conclusion](https://groups.google.com/a/chromium.org/d/topic/ct-policy/fCt4Bm03GsI/discussion) announcing that Chrome would not support name redaction as part of their enforcement action on Symantec.

In general, most CAs favor name redaction (mostly because their customers want it for perceived privacy or security reasons), and Microsoft favors name redaction (mostly because they and others want it for perceived PR/branding management reasons).

Comodo is an author of the CT and name redaction spec, though has expressed ambivalent and shifting views on whether name redaction is a good idea. Let's Encrypt has expressed strong opposition to name redaction. 

FWIW, I have expressed consistently strong opposition to name redaction, as something that significantly increases the complexity and risk of mistakes in CT-enforcing clients, and as being far too driven by enterprise security-through-obscurity instincts (expressed as customer demand to CAs). 

There exist other mechanisms to achieve the same result for truly private labels, such as wildcards for indefinitely private labels, and privately trusted certificates for ephemerally private labels. Both have other security/operational tradeoffs associated with them, but both represent the domain owner absorbing the costs of their leasing public trust for private matters when it really matters to them, rather than having a free hand to push that cost onto the client ecosystem.

**Comment by lachellel** [comment]
- I think we've primarily agreed that there will be no name redaction. 
- This is for Public Trust
- Not inclusive of enterprise (internal govt)

Let's get some agreement and close **or** address?

**Comment by konklone** [comment]
Largely :+1:, though I wouldn't say `Not inclusive` of enterprise -- you could still use this PKI for internal certificates if you were comfortable with the hostname appearing publicly.
