### ISSUE TITLE
Commercial TLD Use

### ISSUE THREAD

**Issue by hlieberman-gov** [uspki/policies#151]
In the policy, right now we're restricting ourselves to .mil and .gov TLDs.  There are a number of domains, however, that are military in nature but on other TLDs (.us, .com).  National Guard, in particular, use a variety of non-.mil/.gov TLDs.

Is there a way to expand this list to include them?

Examples:
- goang.com
- goarmy.com
- vtguard.com
- nationalguard.com

**Comment by lachellel** [comment]
> Is there a way to expand this list to include them?
Early discussions were included in #12 

We are focused on Technical Constraints at both the policy level and the Intermediate / Issuing CA level (name constraints).  A government root and issuing boundaries needs to be _constrained_ in some manner. 

There are executive branch level policies that restrict executive branch government websites to dotgov and dotmil domains.  And yes, there are exceptions in place!  Rather than focusing on the exceptions, we were focusing on the 95% rule so that the trust store + browser + public community can apply those same expectations (technical constraints).  

 .com and .us would change the certificate policy and the approaches, and potentially expand beyond a reasonable boundary.  Do you think it's worth it?

**Comment by techliaison** [comment]
If there is a known and relatively small list of exceptions they could potentially be added in to the constraints in the CP and included in name constraints given to 1 or more specific issuing CAs, without opening the root to all of .com or .us

I'm not advocating for the change, just mentioning it as a possibility if there is a known list of exemptions up front and it is not likely to be an ever increasing list.

**Comment by konklone** [comment]
@hlieberman-gov This has come up before, and we've generally opted for the tighter constraints. This keeps our policies simple, it keeps technical client enforcement simple. We think this is likelier to result in more consistent security boundaries and stronger understanding in the WebPKI community about the risk our root creates.

It also helps that goarmy.com and other public-facing services that are designed for use by the public (rather than agency staff) continue to have options, in the form of commercial certificates.

**Comment by hlieberman-gov** [comment]
@konklone, I certainly understand your first point about keeping policies simple.  I'm less sure about whether it actually makes a practical difference in terms of client enforcement -- as far as I've seen, Name Constraints isn't really going anywhere that quickly.

I'm a little hesitant to simply handwave commercial certificates here -- but it's not a hill I'm willing to die on. ;)

**Comment by konklone** [comment]
> I'm a little hesitant to simply handwave commercial certificates here -- but it's not a hill I'm willing to die on. ;)

Well, I understand how painful it is at DoD to get those -- that's a big part of the point for this project. But I would also hope that DoD would find it easier to approve commercial certificates for the class of things that are already so exceptional that they exist outside the `.mil` network and DNS, and once they have a PKI in place that supports `.mil` for both internal staff and public users without friction.

**Comment by LarryFrank** [comment]
Thought this was resolved already (in the thread on technical constraints?).  Some are already using commercial PKI certs (suspect most are).  If they are happy with DoD PKI certs - they can continue to get them as that doesn't fall under the "public trust" PKI.  As I said on the call today - will be some complaints from DoD about the restriction but the majority will understand.

**Comment by lachellel** [comment]
This CP and associated services (CAs) is limited to .gov and .mil
