### ISSUE TITLE
5.1.3 Power and Air Conditioning

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#155]
The requirements as currently defined in draft: 

1) Are focused on a single physical implementation pattern
2) Assume Repositories are **not** using a distributed environment or implemented in hot/hot DR   

Suggest these requirements are updated to be outcome oriented, and focused on Availability requirements versus explicit implementation patterns. 

> ### 5.1.3 Power and air conditioning
> The CA SHALL have backup capability sufficient to lock out input, finish any pending actions, and record the state of the equipment automatically before lack of power or air conditioning causes a shutdown.  
> 
> The repositories (containing CA certificates and CRLs) SHALL be provided with uninterrupted power sufficient for a minimum of 6 hours operation in the absence of commercial power, to maintain availability and avoid denial of service.

**Comment by LarryFrank** [comment]
I am not sure I agree this is really "implementation specific" - at some level, a running CA needs to shut down cleanly rather than lose data and no matter how it is implemented, the LAST instance can actually fail.
DoD does have distributed environments for CAs and repositories (some single instance hot/hot and some active/active.)  Implementations are load balanced and have automated fail over and still finds these requirements appropriate to ensure high reliability.  And, DoD requires that systems have testable requirements for things like this.  Frankly, I think a lot of the commercial policies are way too loose on things like this - but maybe they don't consider them "mission critical" functionality like DoD does.

**Comment by grandamp** [comment]
IMO:  Perhaps the requirements should align with: https://nvd.nist.gov/800-53/Rev4/impact/high

Or, refer/defer to it?

**Comment by LarryFrank** [comment]
I prefer to leave 800-53 to the RMF people.  The PKI needs to be accredited - but the CP typically is about stuff that RMF doesn't directly address or (like power) where it doesn't supply any real details.  So the one on power (PE-11) says "The organization provides a long-term alternate power supply for the information system that is capable of maintaining minimally required operational capability in the event of an extended loss of the primary power source. "  But to be useful as a requirement - needs someone to define what "minimally required operational capability " is and specify for how long (2 minute or 2 days or...)  The two statement above  define what is the minimum operation capability for the CA and the repository and the length of time power is needed for each.

**Comment by lachellel** [comment]
closed by PR #498
