### ISSUE TITLE
Policy OIDs - To define or not define federal policy oids (policy mapping)

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#27]
Section 1.2

>The following Certificate Policy identifiers are reserved for use by CAs as an optional means of asserting compliance with this CP (OID arc 2.23.140.1.2) as follows:

Pull request #10 comment / question on whether to assert a policy mapping / federal OIDs

**Comment by lachellel** [comment]
My 2 cents:  _Unnecessary for public trust_

For transparency, reference to NIST CSOR PKI Object Registration: http://csrc.nist.gov/groups/ST/crypto_apps_infra/csor/pki_registration.html

**Comment by lachellel** [comment]
@dcooper16  for thoughts

**Comment by lachellel** [comment]
Referencing for the discussion: 

Section 7.1.6 of BRD: 
- https://github.com/uspki/policies/blob/master/certificate-policy.md#716-certificate-policy-object-identifier

And 7.1.6.4 Subscriber Certificates: 
- https://github.com/uspki/policies/blob/master/certificate-policy.md#7164-subscriber-certificates

I might revert my 2 cents statement (_now worth zero cents_) and state that it might be a good idea to define an OID arc and comparable policy identifiers.

**Comment by LarryFrank** [comment]
> I might revert my 2 cents statement (now worth zero cents) and state that it might be a good idea to define an OID arc and comparable policy identifiers.

Do we need a separate "fed policy OID" for each of the CA/B OIDs or a single Fed OID that is always asserted for this policy and then also assert the specific CA/B OID for the cert type?   Also, CA/B baseline says "should" for their OIDs in Section 7 (i.e., optional) - I think that should be "shall".

**Comment by pzb** [comment]
See http://aka.ms/rootcert#A_Root_Requirements item 15.  The BRs say _should_ but the Microsoft policy is _must_.

**Comment by lachellel** [comment]
thanks @pzb 
pulling the reference in for easier review

Microsoft policy

15. CAs must use  the following OIDs in the end-entity certificate: DV 2.23.140.1.2.1; OV 2.23.140.1.2.2; EV 2.23.140.1.1.; IV 2.23.140.1.2.3; EV Code Signing 2.23.140.1.3; Non-EV Code Signing 2.23.140.1.4.1.

**Comment by LarryFrank** [comment]
> Microsoft policy
OK with shall for the CA/B forum defined OIDs.  Recommend we say "shall" for them. 

That does not directly answer whether there needs to be one or more federal OIDs defined and used.  

@lachellel
> it might be a good idea to define an OID arc and comparable policy identifiers.

I am not seeing why it might be (I like @lachellel original 2 cents...)

**Comment by lachellel** [comment]
this is what happens when you sit down and read NIST Standards, dozens of CPs and CPS docs, the BRD, (etc) when everyone else is on holiday :+1: 

The _may, must, should, shall_ all blur together. 

It was this MUST and MAY that I was trying to unravel: 

- A Certificate issued to a Subscriber MUST contain one or more policy identifier(s), defined by the Issuing CA, in the Certificate's certificatePolicies extension that indicates adherence to and compliance with these Requirements. CAs complying with these Requirements MAY also assert one of the reserved policy OIDs in such Certificates.

**Comment by LarryFrank** [comment]
>It was this MUST and MAY that I was trying to unravel:
•A Certificate issued to a Subscriber MUST contain one or more policy identifier(s), defined by the Issuing CA, in the Certificate's certificatePolicies extension that indicates adherence to and compliance with these Requirements. CAs complying with these Requirements MAY also assert one of the reserved policy OIDs in such Certificates.

They can get weird trying to unravel the threads! 

To me, this says that all issuing CAs do need to define and assert a policy OID of their own and can also assert one of the CA/B Forum OIDs (assuming compliance).  

If accurate, that, means that we need to define at least 1 federal policy OID that can be asserted in CA and subscriber certs.  And, since Microsoft seems to be demanding the CA/B forum OIDs, the CAs also need to assert the appropriate one of those, too.

**Comment by lachellel** [comment]
@LarryFrank I've hit a wall on this one.  I put a placeholder into #147 for federal OIDs but it can be taken out just as easily.  Registering new OIDs with CSOR won't be a problem either.

**Comment by techliaison** [comment]
we added an OID to common policy for "publicly trusted serverAuth" certs that no one has started to use - I was planning to start a change proposal to pull it out of Common once we have the NPE CP ready since we won't want any certs issued under Common that are intended for that purpose. So we could just use that OID NIST already gave us.  although I don't know if we need 2 - one for DV and one for OV or if we just relying on the different CABForum OIDs to make that distinction and only need 1 specifically to say it is a government issued serverAuth cert.

**Comment by lachellel** [comment]
policy oid discussion notes: 

- we'll add govt specific policy oids, under CSOR OID Arc
- incorporate / assert both
- yes, it creates bloat in a cert
- purpose is not for path processing constraints
- purpose is informational 

lachellel only note:  _while writing this, it seems the purpose notionally agreed upon is somewhat duplicative to other mechanisms (policyQualifier)_

**Comment by lachellel** [comment]
one last pass on to policy oid or not to policy oid...stays open until CSOR OIDs requested and assigned...

**Comment by LarryFrank** [comment]
I vote for having a specific OID - I read that as a CA/B requirement.  And also assert the CA/B reserved OV or DV OID as appropriate for Microsoft and others who seem to care.

**Comment by lachellel** [comment]
I closed this issue a bit too soon - we added the placeholders but didn't have the policy oids in hand. 

Policy OIDs confirmed as assigned by NIST, under [CSOR](https://csrc.nist.gov/Projects/Computer-Security-Objects-Register/PKI-Registration): 


2.16.840.1.101.3.2.1.3.43  id-fpki-pubtrust-tls-dv  
2.16.840.1.101.3.2.1.3.44  id-fpki-pubtrust-tls-ov
