### ISSUE TITLE
Where should a CT requirement go in the CP or CPS?

### ISSUE THREAD

**Issue by konklone** [uspki/policies#37]
If we want SCT obtainment and embedding in certificates to be required for all issuing CAs, where is the appropriate place to include this process in the CP or CPS?

**Comment by lachellel** [comment]
Per @techliaison feedback

Section 4: 

- 4.3 - https://github.com/uspki/policies/blob/master/certificate-policy.md#43-certificate-issuance
- 4.6 - https://github.com/uspki/policies/blob/master/certificate-policy.md#46-certificate-renewal
- 4.7 - https://github.com/uspki/policies/blob/master/certificate-policy.md#47-certificate-re-key
- 4.8 - https://github.com/uspki/policies/blob/master/certificate-policy.md#48-certificate-modification

**Comment by LarryFrank** [comment]
> If we want SCT obtainment and embedding in certificates to be required for all issuing CAs, where is the appropriate place to include this process in the CP or CPS?

So, I read this and though the question was CP or CPS...  But rereading, I think it is what paragraph.  Recommend 4.3.1 "CA Actions During Certificate Issuance."  If renewal, rekey and modification are supported, should be in 4.x.3 for each.  Since (as I understand it) there is also something included in the certificate itself, there should be something in the certificate profile section also...

**Comment by aakunz** [comment]
Agree w/Larry on placing multiple references in the CPS to describe the required practice wherever it applies. It should also get a general introduction in the CP only as part of the overall policy for the PKI, perhaps explaining the "why" but not any of the "how" which will be found in the CPS.

**Comment by lachellel** [comment]
Chrome and EV and CT (snip) - May 2016

In order to improve the security of Extended Validation (EV) certificates, Google Chrome requires
that all certificates issued after 1 Jan 2015 be CT Qualified in order to be recognized as EV.

1. An SCT from a log qualified at the time of check is presented via the TLS extension OR is
embedded within a stapled OCSP response;
AND there is at least one SCT from a Google Log, qualified at the time of check, presented
via any method;
AND there is at least one SCT from a nonGoogle
Log, qualified at time of check,
presented via any method.
2. An Embedded SCT from a log qualified at the time of check is presented;
AND there is at least one Embedded SCT from a Google Log, once or currently qualified;
AND there is at least one Embedded SCT from a nonGoogle
Log, once or currently
qualified;
AND there are Embedded SCTs from AT LEAST the number of logs once or currently
qualified shown in Table 1.

| Lifetime of certificate | Number of SCTs from distinct logs |
|--- | --- | 
| <15 months | 2 |
| >= 15, <= 27 months | 3 |
| > 27, <= 39 months | 4 |
| > 39 months | 5 |

**Comment by lachellel** [comment]
Discussion: not just for EV?

**Comment by LarryFrank** [comment]
>  Discussion: not just for EV?

I don't see a need to differentiate (assuming the world will go there eventually) but really is beyond my expertise.  Certainly need to ensure CAs can do it...

**Comment by weirdscience** [comment]
Google Chrome announced at the last CAB Forum F2F meeting CT will be a requirement of all public Server Auth certificates.

"This past week at the 39th meeting of the CA/Browser Forum, the Chrome team announced plans that publicly trusted website certificates issued in October 2017 or later will be expected to comply with Chrome’s Certificate Transparency policy in order to be trusted by Chrome. "

Current policy is located here. https://www.chromium.org/Home/chromium-security/root-ca-policy

The Google CT log is free and the API is located on github. https://github.com/google/certificate-transparency. Waiting to here back from other log operators if there is a cost to use and instructions.

If USG decides to operate its own log, here is Chrome policy on CT log inclusion. https://sites.google.com/a/chromium.org/dev/Home/chromium-security/certificate-transparency/log-policy

**Comment by lachellel** [comment]
Bumping this one to the top of the list again - referencing #80 **and** where / how to standardize CT for USG server auth certs.  

If we require embedding in the certificates, we have a chicken / egg challenge.  aka the Log(s) chosen need to be qualified and trusted at the time of issuance **and** at the time of validations.

**Comment by LarryFrank** [comment]
> If we require embedding in the certificates, we have a chicken / egg challenge. aka the Log(s) chosen need to be qualified and trusted at the time of issuance and at the time of validations.

What will be "qualified and trusted" at some time in the future cannot be something the CA is required to know at the time of issuance - it can only know what it knows at time of issuance.  The question in my mind - if one or more of the chosen logs becomes "unqualified and/or untrusted" - what does a CA do about it?  Revoke the cert?

**Comment by konklone** [comment]
In practice, even if you don't require embedding in the certificates, that's functionally going to be what's required for a long time. 

The other methods of serving SCTs are through OCSP stapling responses and through the TLS connection itself (via an extension). These methods are pretty much done only by orgs that do custom TLS termination, as they are not common in open source servers or commonly found proprietary termination devices. 

For example, to meet Chrome's CT requirement, Symantec's been embedding SCTs in every certificate they issue.

There are 3 log removals I'm aware of from Chrome's set of trusted logs. Each of these contains the impacts to site operators and to CAs:

* Izenpe: https://groups.google.com/a/chromium.org/d/topic/ct-policy/qOorKuhL1vA/discussion
* Certly.IO: https://groups.google.com/a/chromium.org/d/topic/ct-policy/nyRtXSWSeaM/discussion
* Google Aviator: https://groups.google.com/a/chromium.org/d/topic/ct-policy/u87C79AY-E8/discussion

In no case did it cause existing certificates to become untrusted. However, in all cases they did require CAs to fairly rapidly (~2 weeks) change which logs to which they would be subsequently logging future certificates.

**Comment by techliaison** [comment]
Just a question as I was looking to find examples of SCTs currently embedded in certificates –
I was not very explicit in stating how these would be embedded in a certificate – do we want to say whether to use V1 or V2 format?
Looking at RFC 6962-bis there appears to be a difference at least in the OID used to identify them.

**Comment by weirdscience** [comment]
I drafted a Google Trust Store PR #112 and #116 which included CT requirements in section 4.3.1. Because TLS stapling is more on the relying party than the CA, I went with the embedded option.

The certificate profile should be update to be specific about which TLS extension includes the SCT.

**Comment by LarryFrank** [comment]
I think we decided 4.4.2 - so I did that...
