### ISSUE TITLE
Certificate Profiles: Intermediate CA

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#459]
[Consolidated from comments received via email.]

**Organization / Program:** DoD
**Section:** Certificate Profile - Intermediate
**Comments:**

|  Line | Comment | Suggested Change |  
| --- | --- | --- |
| SIA | | Also add media type to be application/pkix7-mime in the content-type header field and file extension to be p7c |
| basic constraints | While path length is a weak security mechanism due to self-issued certificates, its inclusion limits adversary's choices.  It should be recommended or required for online CA certificates.  In other words, if an Intermediate CA is offline, its certificate need not have path length constraint. |Make path length RECOMMENDED or mandatory |
| EKU | It is unclear what it means for an EKU to be consistent with another EKU.  EKUs need to be consistent with KU.  KU is, strictly speaking a function of ciphersuite.  I would just delete this since EKU in the end entity certificates need to be consistent with KU in the end entity certificate. | Delete the phrase after the comma |
| EKU | In order to enure that clients that enforce EKU on path, add the OCSP Signing to the list of mandatory EKU | Add OCSP Signing to the list of mandatory EKUs |
| AIA | CA Issuer field is too restrictive and incomplete.  All the CA issuers will be one certificate and hence .cer should also be permitted. Recommend using language suggested. | The HTTP pointer can be to a single DER encoded certificate.  The media type should be application/pkix-cert in the content-type header field of the response.  It is recommended that this resource be a .cer file for ease of interoperability. <br>Alternatively, the HTTP pointer can be to a collection of certificates.  The media type should be application/pkix7-mime in the content-type header field of the response and should contain the “certs-only” CMS message.  It is recommended that this resource be a .p7c file for ease of interoperability.  |
| CRL DP | Due to the fact that the Issuer of the CA certificate will not issue end entity certificates, it is recommended that the CRL be full and complete (as opposed to partitioned).  This will also ensure security since clients may nor process partitioned CRLs properly.  Also note that the CRL profile calls for a full and complete CRL. |  Add a statement that the URL shall point to full and complete CRL. |
| Name Constraint | Directory names are permitted since Subject DN is directory name | Delete the statement in profile and in CP that directory names are not permitted. |
| Name Constraint | E Mail address constraint is mentioned but not listed | An easy way to enforce no e-mail address is to have a.gov string in both permitted and excluded subtrees for e-mail address name form |
| General | It is not clear how the extensions listed for the profile were chosen. | Either only list the extensions used or list all the extensions from RFC 5280 4.2.1 and list which ones are not used.  The missing extensions are policy mapping; and freshest CRL. | 
| Issuer Alt Name |  | Use the Root CA profile approach of not listing criticality of extensions not used.  Examples include IAN and SDA | 
| Sub Dir Att |  | Use the Root CA profile approach of not listing criticality of extensions not used.  Examples include IAN and SDA | 
| Policy Constraint | | Make this extension critical per RFC 5280 |

**Comment by lachellel** [comment]
See notes in #458 for:

- content-type header (AIA and SIA) discussion
- RFC references updates

**Comment by lachellel** [comment]
@dcooper16 @techliaison

One question - on the Policy Constraints.  The topic comes up like clockwork. 

- Extension: criticality = true or criticality = false? 

Submitted comments are to make critical (true) and topic was discussed in policy discussions.  Federal PKI profiles state: 

> Applications that support policyMapping must also support the policyConstraints extension and RFC5280 requires this extension be marked critical.  This profile, however, recommends setting the criticality to false to enable greater interoperability.

**Comment by dcooper16** [comment]
X.509 states that the policyConstraints extension may be marked as either critical or non-critical, and I disagree with RFC 5280 mandating that it be always marked critical. As I recall, this was based on a general decision to mandate that an extension be marked critical whenever the processing of the extension **could** affect the results of path validation, rather than allowing the issuer to consider the pros and cons in any given situation.

In the case of the FPKI, some relying parties will want to make decisions based on policy and some will just ignore the policies in the certificates, and there doesn't seem to be any reason to require an application to reject a certificate just because it couldn't process a policy-related extension if it was just going to ignore the policy information anyways.

In the case of this PKI, what would be the reason for including a policyConstraints extension? I don't see any reason to assert inhibitPolicyMapping, since there is no mention of including policyMappings extension. Besides, isn't the idea to have a two-level hierarchy, in which case the subject of the CA certificate would only issue end-entity certificates? I also don't see any reason to assert requireExplicitPolicy, since this is a hierarchical PKI and it wouldn't make sense to issue certificates that couldn't be accepted by any relying parties (because they don't assert a policy that is also asserted in the CA certificate(s) in the path).

**Comment by grandamp** [comment]
I agree that this should not be asserted, as [Mozilla does not support the use of this extension.](https://github.com/18F/fpki-testing/issues/1#issuecomment-185396943)
