### ISSUE TITLE
Section 5.2.1: Remove operator role

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#485]
[This issue is being opened to separate the comment from #468 general editorial comments. ] 

Organization / Program: Slandala 
Section: 5.2.1 
PDF Page: None
PDF Line(s): 1173
Comment: Increasingly the operator role is not used by anyone.  It may be used for network support, tape operators (where they still exist), or possibly even the guy he has to come in each week to fix the air conditioner; but typically the admins are also operators.

Suggested Change: None

**Comment by lachellel** [comment]
This is a valid comment.  Marking for discussion.

**Comment by LarryFrank** [comment]
The 4 roles (Officer, Admin, Auditor and Operator) in this CP are a legacy of an old NIAP CA profile which specified those roles and the Fed PKI CPs which embedded those roles.  The operator is somwhat unique in that any other role may also act as the operator...  

Ultimately, you end up with 3 mandatory roles:  Officer (person doing the RA type role remotely or on the CA), Sys Admins, and Security (called an "auditor" which confuses people because it is NOT the compliaince auditor - so overloaded).

I would be fine with adding the "operator" functions to the Sys Admin role and deleteing the Operator...

**Comment by lachellel** [comment]
@LarryFrank 

- For the Security role - after updating Section 8, +1 to the "confusing to name this an audit administrator"
- If we use Security - how should this relate to the ISSO (information system security officer) too?  They perform the type of duties defined (overseeing) and it should either **be** the same or further clarified.

**Comment by LarryFrank** [comment]
> •If we use Security - how should this relate to the ISSO (information system security officer) too? They perform the type of duties defined (overseeing) and it should either be the same or further clarified.

The trusted role on the CA can be the ISSO or IAO or System Security Officer.  It just isn't the complaince auditor.   Whatever name you give that role should be consistent throughout.
