### ISSUE TITLE
Section 4.2.1 Performing id and authn functions

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#50]
Federal PKI Device Policy needs to respond to this requirement not parrot it:
"The CA SHALL develop, maintain, and implement documented procedures that identify and require additional verification activity for High Risk Certificate Requests prior to the Certificate's approval, as reasonably necessary to ensure that such requests are properly verified under these Requirements."
e.g.  "The FPKI SHALL maintain a list of names at higher risk for phishing or other fraudulent usage, names contained in previously rejected certificate requests or revoked Certificates, or names that have been identified using an FPKI risk-mitigation criteria.  The CA SHALL review all certificate requests against this  identify High Risk Certificate Requests.  Once identified, High Risk Certificate Requests SHALL be flagged for additional review, which SHALL include contacting the Applicant Representative for certificate request verification and obtaining a secondary authorization from an Agency Authorizing Official." 
(note: this is suggested place-holder language only).

**Comment by LarryFrank** [comment]
> Federal PKI Device Policy needs to respond to this requirement not parrot it:

No - policy states requirements not how things are done. - CPS has to "respond" to the requirement.

**Comment by lachellel** [comment]
Comment on Section 4.2.1: 

- https://github.com/uspki/policies/blob/Section4-updates/certificate-policy.md#421-performing-identification-and-authentication-functions
- See branch _section4-updates_ and PR #137

There are conflicting statements between the original baseline requirements and the current proposed edits for Section 4.x, lifecycle events, and time elapsed.  It starts with Section 4.2.1:

_Original:_ 

> Section 6.3.2 limits the validity period of Subscriber Certificates. The CA MAY use the documents and data provided in Section 3.2 to verify certificate information, provided that the CA obtained the data or document from a source specified under Section 3.2 no more than **825** days prior to issuing the Certificate.

_New:_ 

> Identification and authentication as specified in Sections 3.2 SHALL occur no more that **30** days prior to certificate issuance

Conflicts: 
-  Original states 825 days prior to issuing the certificate
-  We dropped this value to 30 days
-  I believe this time period (825 days) is at the core of the differences in terminology and understanding used in federal pki versus web pki, and the root cause of some confusion.   From 4.2.1 - the identity and authentication must have occurred within the last 825 days.  The timeline and lifecycle events could be: 
  - **Day 1**: 3.2 Identity and Authentication
  - **Day 2**: Device certificate issued, with a validity period of 365 days
     - Day 2 + 365= End of validity period @ Day 367
  - **Day 367**:  Device certificate renew/rekey (_does not matter - a new certificate is being generated_).  Is information time valid ( Day 367 - Day 1 < 825)?  Is the information the same and has not changed (no changes to FQDNs)?  If yes, new cert with a validity period of 365 days
      - Day 367 + Day 365 = End of validity period @ Day 732
 - **Day 732**:   Device certificate renew/rekey (_does not matter - a new certificate is being generated_).  Is information time valid ( Day 732 - Day 1 < 825)?  Is the information the same and has not changed (no changes to FQDNs)?  If yes, new cert with a validity period of 365 days
    - Day 732 + Day 365 = End of validity period @ Day 1079
 - **Day 1097**:   Device certificate renew/rekey (_does not matter - a new certificate is being generated_).  Is information time valid ( Day 1097 - Day 1 < 825)?  No.  
-  Redo 3.2 Identity and Authentication check.  Clocks starts again at Day 1. 


**Questions:** 

- Why drop the value to 30 days? 
- Isn't Section 4.2.1 applicable **regardless** of the lifecycle type of event (initial issuance, renewal, rekey) and therefore Sections 4.6.3 and Section 4.7.1 edits are invalid: 
  - Section 4.6.3 and edits proposed: 
  > The CA SHALL verify that the new certificate expiration date SHALL NOT exceed **36 months** from the date of initial certificate issuance.
  - Section 4.7.1 and edits proposed:  
  > Certificates may be rekeyed if is has been less than **9 years** since the initial certificate was issued based on identity proofing as specified in Section 3.2 and issuance as specified in Section 4.1-4.4

**Comment by lachellel** [comment]
@LarryFrank @jaspenc @weirdscience @techliaison

**Comment by LarryFrank** [comment]
First - section 4.2.1 is unrelated to 4.7... so, NO - it applies to initial issuance - requirements related to renewal, rekey and modification (4.6, 4.7, 4.8) all have their own SEPARET sections - so 4.2.1 does not apply to them. 

The "30 days" is a current gov CP requirement related to the amount of time that can exist between completion of identity proofing and the actual issuance of the certificate.  Unrelated to how long the data is "good" - or has to be re-verified.

**Comment by lachellel** [comment]
@LarryFrank 

That logic _might_ fail unfortunately in Web PKI.  This is what I meant by the difference in federal pki and web pki.  

If 4.2.1 was only related to initial issuance only, then it would actually be in Section 4.3 Certificate Issuance.  Section 4 covers the actions for **all** lifecycle.  Identity and Authentication is Section 4.2. 
 Renewal, Rekey and Modification have their own sub-sections (4.6, 4.7, 4.8) and are only separate for what notification and request actions are - not the Identity and Authentication validity period. 

I put it on the agenda for tomorrow to discuss + reviewing CP/CPS samples + other public discussions on this very topic.

**Comment by LarryFrank** [comment]
So, I strongly disagree.  4.6, 4.7 and 4.8 parallel 4.1, 4.2 4.3 and 4.4.  For example - 4.7.3 is "processing certificate re-key requests" which lines up with 4.2.  And there is a different "Section 3" (3.3) section for I+A for rekey. But we are arguing about what other people think - which is rarely useful.  I recommend saying what we believe is the right thing to say and let them tell us we are wrong instead of handcuffing ourselves to what we think they want.  They can certainly tell us NO - which is why we are doing this in a public forum!

**Comment by lachellel** [comment]
Yes, that is why I posted it here - so we could debate the nuance openly!  Always a pleasure Larry.   :+1:
