### ISSUE TITLE
CA Certificate Profiles: OCSP Signing EKU

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#515]
A new comment was submitted regarding the EKUs in the CA certificate profiles.   

**Issue:** 
-  Add OCSP signing to the EKU value asserted in CA certificates

**Impacts:**
- [Root CA certificate profile](https://github.com/uspki/policies/blob/master/certificate-profile-root-CA.md)
- [Subordinate CA certificate profile](https://github.com/uspki/policies/blob/master/certificate-profile-subordinate-CA.md)
- Section 7 of this CP

**Actions:**
- Review the trust store and Baseline Requirements policies again
- Review other entity CA certificates for clarity 
- Sample the ocsp responses, ocsp certs, and processing in libraries 
- Update profiles and policy based on outcomes

**Comment by techliaison** [comment]
why add an EKU to the Root CA certificate?
The Root will be using a delegated OCSP responder and not using its own key to sign the responses.

**Comment by lachellel** [comment]
I'm just adding the received comment for tracking here first.  :grinning:

**Comment by Chokhani** [comment]
The reason for including EKU in Sub CA certificate is that this certificate already has EKUs and since Sub CA will issue delegated OCSP Responder certificate, it is safest from interoperability perspective to add the EKU.  Otherwise, clients processing OCSP Responder certificate chain (those who enforce EKU constraints on the chain might fail.

We are not asking to add EKU to root certificate.  However, if the root is promulgated with restrictive EKU properties (which it should) OCSO Signing should also be added to those

**Comment by Chokhani** [comment]
Folks are confusing root properties with contents of X.509 root certificate.  Root properties are metadata associated with the root by a given environment

**Comment by ryancdickson** [comment]
Sample Certificates updated in Pull Request: # 507 - "Upload updated Test Certs"

**Comment by lachellel** [comment]
Reviewed four providers and samplings of CA certs (intermediate issuing, and roots just for good measure): 

- Goog
- Digicert
- Comodo
- LE

Haven't found a single CA cert that asserts the EKU yet.  It would be nice to understand which clients that are targeted for this use case (TLS, webpki) actually would fail.

**Comment by Chokhani** [comment]
It does not matter.

 

It is safer to assert the OCSP Signing EKU in CA certificate in order to perform the delegation properly

**Comment by Chokhani** [comment]
OK.

 

I may have been a bit hasty.  What is the e-mail saying?

 

Is it saying that the commercial certificates examined do not have EKU in CA certificates or is this is saying that the CA certificates have EKU, but do not have OCSP Signing EKU?

 

Also, note that the comment was to add the OCSP Signing to Server Auth and hence why would web PKI fail?

 

The use case for adding OCSP Signing EKU in case EKU is present is to accommodate clients that force EKU on the path and thus ensure that the OCSP certificate path will succeed.

 

Once we get on the same page, I can share security considerations if they are relevant.

 

From: Santosh Chokhani [mailto:chokhani@libra-sec.com] 
Sent: Friday, August 31, 2018 6:05 PM
To: 'uspki/policies' <reply@reply.github.com>; 'uspki/policies' <policies@noreply.github.com>
Cc: 'Comment' <comment@noreply.github.com>
Subject: RE: [uspki/policies] CA Certificate Profiles: OCSP Signing EKU (#515)

 

It does not matter.

 

It is safer to assert the OCSP Signing EKU in CA certificate in order to perform the delegation properly

**Comment by rmhrisk** [comment]
Because the inherited EKU behavior inclusion of OCSP signing in a ICA is signaling the parents delegation Of response signing authority (e.g. you can revoke certificates issued by the parent)

As for the CA providers mentioned all do CA signed responses, UAs allways trust the certificate signing key for response signing.

**Comment by Chokhani** [comment]
See inline

**Comment by rmhrisk** [comment]
Yes, I meant certificates issued by the parent.

If I recall forrly most clients ignore KU flags.

Most UAs now implement EKU constraints, not just CAPI.

**Comment by Chokhani** [comment]
See inline.

**Comment by lachellel** [comment]
@Chokhani to close this one out: 

**Question:** Do these CA certificates have EKUs or not?
**Answer:** Yes.  The issuing CA certs have EKUs as do our profiles.  You can review these and others at their repositories or query crt.sh for other samples.

**Comment by lachellel** [comment]
Re-open this one.  The conversations were unclear - review samples again. 

Question: Do these CA certificates have EKUs or not?

**Comment by Chokhani** [comment]
Yes; they do and that is where the rub is.  They have some EKUs and not OCSP.
