### ISSUE TITLE
Mozilla Trust Store Policy v2.5 Requirement on CCADB, Bug Submissions, and Ownership/Operational Changes

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#525]
The latest Mozilla CP has requirements for CCADB and Bug submissions for specific categories of incidents and events such as:

- Revocation of an intermediate CA (bug report and ccadb)
- Misissuance (bug report and ccadb)
- audit submission (ccadb)

Since it mentions a specific product, the root should have a SOP for how and timelines for submitting the above reports/bugs. Also, it needs to be enforced somehow between the root and issuing CAs.

Also contains specific requirements for :

- notification and verification of change of ownership or control of the CA certificate or operational personnel through contracts or acquisition.
- notification and procedures for physical transfer of private key.

These should be applied consistency to any CA under the CP. I will start a new PR to incorporate the specific requirements.

**Comment by lachellel** [comment]
For these three bullets: 

- Revocation of an intermediate CA (bug report and ccadb)
- Misissuance (bug report and ccadb)
- audit submission (ccadb)

Some of these might already incorporated into the CP?  We do mention the CCADB.

- https://github.com/uspki/policies/blob/master/certificate-policy.md#23-time-or-frequency-of-publication
- The timelines for the CAs are 15 days to the policy authority
- We should add the misissuance and revocation requirement
- We might want to update 2.2 as well
- An SOP is out of scope for the CP  

For this item: 

- notification and verification of change of ownership or control of the CA certificate or operational personnel through contracts or acquisition
-  Assume this is a summary of 8.2: https://github.com/mozilla/pkipolicy/blob/master/rootstore/policy.md#82-change-in-operational-personnel
- This may never occur for USG but we can review with general counsel 

For this item: 
- notification and procedures for physical transfer of private key.
- Assume this is a summary of 8.3: 
https://github.com/mozilla/pkipolicy/blob/master/rootstore/policy.md#83-change-in-secure-location
- this may never happen for USG because it's dependent upon 8.1 or 8.2 occurring first?

**Comment by weirdscience** [comment]
It's more close potential disparities so the root or FPKIPA know what to do with the reports after we receive them.

Correct on the other items and half agree depending on interpretation:

- 8.1 Change in ownership - The intent seems to ensure the owner understands the requirements. If this will never happen and we should add CA's never change owners and are decommissioned.
- 8.2 Change in operational personnel - The intent seems to ensure if a CA has core functions operated by a contractor, then the contractor can operate according to the policy.
- 8.3 Change in Secure Location - Independent of 8.1 and 8.2 but may apply with either. Crypto module transfer may happen if a CA operator moves data centers or changes operational locations.

**Comment by lachellel** [comment]
For 8.3, it's not independent of 8.1. and 8.2? 

> The section applies when **section 8.1 and/or section 8.2 applies, and** when the cryptographic hardware related to a certificate in Mozilla's root store is consequently moved from one secure location to another.

It might be an interpretation nit.  Reading all of section 8 in the mozilla policy, I see it as applying a must (shall) statement only when 8.1 and/or 8.2 is also true.

**Comment by weirdscience** [comment]
Sorry, I misunderstood your question for 8.3. You're correct. I'll answer your other comments in #527

**Comment by weirdscience** [comment]
Discussed this at a WG meeting and all are moot since the US Government will always be the owner and operator.
