### ISSUE TITLE
Section 4.7.1: Clarify that CA certificates are included in the requirement for no rekey 

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#533]
Section 4.7.1:

- Current requirement states there are no rekeys allowed
- Comments on CPS development suggest rekeys for the CA certificates (including root)

- [ ] Action: Clarify in Section 4.7.1 that no rekeys are allowed for CA certificates

Example Microsoft trust store requirements and suggestions: 

> Private Keys and subject names must be unique per root certificate; reuse of private keys or subject names in subsequent root certificates by the same CA may result in random certificate chaining issues. CAs must generate a new key and apply a new subject name when generating a new root certificate prior to distribution by Microsoft.

While "random" (_random certificate chaining issues_) is a broad statement, the use of rekeys on issuing CAs can also cause chaining issues.

**Comment by techliaison** [comment]
I don't see any reason to change 4.7.1
Comments in the Root CPS are about needing a new CA cert (& therefore new key pair) prior to the expiration of the current Certificate in order to support the requirement that certs issued by a CA can't extend past the lifetime of the CA's certificate. This is section 6.3.2 which should maybe state how long the private key can continue signing certificates which is less than the validity period of the certificate.  So for example the Root can't sign 10 year subordinate CA certs once it reaches the 10 year mark of the Root cert.  The validity period of the subordinate CA's private key depends on the max validity period of the certs it issues.

**Comment by lachellel** [comment]
i'll leave 4.7.1 as is if you think it's not needed.
