### ISSUE TITLE
4.9.7 CRL issuance frequency 

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#63]
12 month validity period for a Root CA that issues certificates to subordinate CAs seems excessive.  Is this the industry standard for device roots?
Recommend FPKI Device Root follow the same CRL issuance as the other FPKI CPS (30 days).

**Comment by lachellel** [comment]
Draft submission under section4 branch: 

- https://github.com/uspki/policies/blob/section4/certificate-policy.md#497-crl-issuance-frequency-if-applicable

> For the status of Subscriber Certificates:
> 
> All CAs SHALL publish CRLs. On-line CAs SHALL update and reissue CRLs at least once every 24 hours and the value of the nextUpdate field MUST NOT be more than seven days beyond the value of the thisUpdate field
> 
> For the status of Subordinate CA Certificates:
> 
> The CA SHALL update and reissue CRLs at least (i) once every 31 days and (ii) within 24 hours after revoking a Subordinate CA Certificate, and the value of the nextUpdate field SHALL NOT be more than 32 days beyond the value of the thisUpdate field.

**Comment by mttcpr2** [comment]
Not much of a disaster recovery window there in the event your CA catches fire (true story) when you boot it up. I'm partial to "monthly issuance" with nextUpdate in the not more than 40 or 45 day vicinity to give adequate time for recovery and allow for some wiggle room around weekends and holidays. Without sufficient wiggle room you're much more likely to end up with a service interruption due to no CRL. That extra wiggle room also allows you to do smarter things with your cache control header so every browser  doesn't end up needing the new CRL in same small window.

**Comment by lachellel** [comment]
Please tell me you have pictures of a CA catching fire?  I'd love to see pics - my imagination might not be as good as the real thing.

**Comment by mttcpr2** [comment]
You can be very certain no pictures were made. The power supply burned up and fried the motherboard, smoke pouring out. Exciting stuff when you're on a raised floor with a fire suppression system.

**Comment by lachellel** [comment]
I believe this one is closed.  Reopen a new issue if needed.
